### ISSUE TITLE
Crash on launch with NoSuchFieldError: ServerLifecycleHooks_handleExit

### ISSUE THREAD

**Issue by JUS4HR** [jrbudda/Vivecraft_118#35]
Tried 1.18.2 and 1.17.1 with java 16 17 and 18, ends up showing the same error. 

```
[13:27:48] [Render thread/ERROR]: Unable to launch
java.lang.reflect.InvocationTargetException: null
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159) [launchwrapper-2.3.jar:2.3]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30) [launchwrapper-2.3.jar:2.3]
Caused by: java.lang.NoSuchFieldError: ServerLifecycleHooks_handleExit
	at dyr.a(dyr.java:1063) ~[dyr.class:?]
	at net.minecraft.client.main.Main.main(Main.java:231) ~[Main.class:?]
	... 6 more
```

Log file: [latest.log](https://github.com/jrbudda/Vivecraft_118/files/8456329/latest.log)

**Comment by mmaniac01** [comment]
Hi JUS4HR,

I'm assuming you're running this in the default directory, so all options (including OptiFine's) are synced between every installation. Try going to a different installation you know will work and disabling shaders if you have them enabled.
Call it a hunch.
