### ISSUE TITLE
Security Craft Cameras crash game

### ISSUE THREAD

**Issue by KingGl1tch** [jrbudda/Vivecraft_118#63]
Whenever I am playing Vivecraft with the Security Craft mod and try to open the cameras my game crashes I hop you fin some way to fix this.

**Comment by wyldcrd** [comment]
Logs? Thx

**Comment by KingGl1tch** [comment]
?

**Comment by KingGl1tch** [comment]
where can i find those?

**Comment by KingGl1tch** [comment]
oh wait is this it

The game crashed whilst unexpected error
Error: java.lang.ClassCastException: class net.geforcemods.securitycraft.entity.camera.SecurityCamera cannot be cast to class net.minecraft.world.entity.LivingEntity (net.geforcemods.securitycraft.entity.camera.SecurityCamera is in module securitycraft@1.9.3.1 of loader 'TRANSFORMER' @48eb001a; net.minecraft.world.entity.LivingEntity is in module minecraft@1.18.2 of loader 'TRANSFORMER' @48eb001a)

**Comment by wyldcrd** [comment]
That’s some of it

**Comment by wyldcrd** [comment]
The rest of it is in your Minecraft folder

**Comment by KingGl1tch** [comment]
oh jeez i think i found all of it


---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 10/8/22, 5:16 PM
Description: Unexpected error

java.lang.ClassCastException: class net.geforcemods.securitycraft.entity.camera.SecurityCamera cannot be cast to class net.minecraft.world.entity.LivingEntity (net.geforcemods.securitycraft.entity.camera.SecurityCamera is in module securitycraft@1.9.3.1 of loader 'TRANSFORMER' @48eb001a; net.minecraft.world.entity.LivingEntity is in module minecraft@1.18.2 of loader 'TRANSFORMER' @48eb001a)
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1622) ~[client-1.18.2-20220404.173914-srg.jar%2364!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,xf:Vivecraft:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,xf:Vivecraft:default,pl:mixin:APP:securitycraft.mixins.json:camera.GameRendererMixin,pl:mixin:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:1260) ~[client-1.18.2-20220404.173914-srg.jar%2364!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,xf:Vivecraft:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,xf:Vivecraft:default,pl:mixin:APP:securitycraft.mixins.json:camera.GameRendererMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.renderSingleView(Minecraft.java:4398) ~[client-1.18.2-20220404.173914-srg.jar%2364!/:?] {re:mixin,pl:accesstransformer:B,xf:Vivecraft:default,re:classloading,pl:accesstransformer:B,xf:Vivecraft:default,pl:mixin:APP:blueprint.mixins.json:client.MinecraftMixin,pl:mixin:APP:securitycraft.mixins.json:camera.MinecraftMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1604) ~[client-1.18.2-20220404.173914-srg.jar%2364!/:?] {re:mixin,pl:accesstransformer:B,xf:Vivecraft:default,re:classloading,pl:accesstransformer:B,xf:Vivecraft:default,pl:mixin:APP:blueprint.mixins.json:client.MinecraftMixin,pl:mixin:APP:securitycraft.mixins.json:camera.MinecraftMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:905) ~[client-1.18.2-20220404.173914-srg.jar%2364!/:?] {re:mixin,pl:accesstransformer:B,xf:Vivecraft:default,re:classloading,pl:accesstransformer:B,xf:Vivecraft:default,pl:mixin:APP:blueprint.mixins.json:client.MinecraftMixin,pl:mixin:APP:securitycraft.mixins.json:camera.MinecraftMixin,pl:mixin:A}
	at net.minecraft.client.main.Main.main(Main.java:284) ~[client-1.18.2-20220404.173914-srg.jar%2364!/:?] {re:classloading,xf:Vivecraft:default}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {re:computing_frames}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.1.51.jar%2317!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%236!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%236!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%236!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%236!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%236!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%236!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%236!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1622) ~[client-1.18.2-20220404.173914-srg.jar%2364!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,xf:Vivecraft:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,xf:Vivecraft:default,pl:mixin:APP:securitycraft.mixins.json:camera.GameRendererMixin,pl:mixin:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:1260) ~[client-1.18.2-20220404.173914-srg.jar%2364!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,xf:Vivecraft:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,xf:Vivecraft:default,pl:mixin:APP:securitycraft.mixins.json:camera.GameRendererMixin,pl:mixin:A}
-- Affected level --
Details:
	All players: 1 total; [LocalPlayer['MrGl1tch'/129, l='ClientLevel', x=-109.22, y=-29.00, z=-5.47]]
	Chunk stats: 225, 132
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,-30,0), Section: (at 0,2,0 in 0,-2,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 43041 game time, 22854 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:516) ~[client-1.18.2-20220404.173914-srg.jar%2364!/:?] {re:mixin,xf:OptiFine:default,re:classloading,xf:OptiFine:default,pl:mixin:APP:blueprint.mixins.json:client.ClientLevelMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:3413) ~[client-1.18.2-20220404.173914-srg.jar%2364!/:?] {re:mixin,pl:accesstransformer:B,xf:Vivecraft:default,re:classloading,pl:accesstransformer:B,xf:Vivecraft:default,pl:mixin:APP:blueprint.mixins.json:client.MinecraftMixin,pl:mixin:APP:securitycraft.mixins.json:camera.MinecraftMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:934) ~[client-1.18.2-20220404.173914-srg.jar%2364!/:?] {re:mixin,pl:accesstransformer:B,xf:Vivecraft:default,re:classloading,pl:accesstransformer:B,xf:Vivecraft:default,pl:mixin:APP:blueprint.mixins.json:client.MinecraftMixin,pl:mixin:APP:securitycraft.mixins.json:camera.MinecraftMixin,pl:mixin:A}
	at net.minecraft.client.main.Main.main(Main.java:284) ~[client-1.18.2-20220404.173914-srg.jar%2364!/:?] {re:classloading,xf:Vivecraft:default}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {re:computing_frames}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.1.51.jar%2317!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%236!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%236!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%236!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%236!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%236!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%236!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%236!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}


-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Mod Resources, moreplayermodels

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 2401239040 bytes (2290 MiB) / 4294967296 bytes (4096 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 9
	Microarchitecture: Kaby Lake
	Frequency (GHz): 3.41
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: NVIDIA GeForce GTX 1060 6GB
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1c03
	Graphics card #0 versionInfo: DriverVersion=31.0.15.1659
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.40
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 56346.99
	Virtual memory used (MB): 19945.88
	Swap memory total (MB): 40000.00
	Swap memory used (MB): 387.30
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G -Xms4G -XX:+UseZGC
	Launched Version: vivecraft-1.18.2-jrbudda-VR-3-r6-forge
	Backend library: LWJGL version 3.2.2 SNAPSHOT
	Backend API: NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 516.59, NVIDIA Corporation
	Window size: 1636x1820
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'vivecraft'; Server brand changed to 'forge'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fast
	Resource Packs: 
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['MrGl1tch'/129, l='ServerLevel[VFNAF]', x=-109.22, y=-29.00, z=-5.47]]
	Data Packs: vanilla, mod:fnaf_mod, mod:forge, mod:moreplayermodels (incompatible), mod:vivecraftforgeextensions (incompatible), mod:securitycraft (incompatible), mod:badmobs, mod:blueprint (incompatible), mod:personality (incompatible), mod:vrapi (incompatible), mod:universalclockhud (incompatible)
	World Generation: Stable
	OptiFine Version: OptiFine_1.18.2_HD_U_H7
	OptiFine Build: 20220410-185216
	Render Distance Chunks: 4
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 516.59
	OpenGlRenderer: NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4
	ModLauncher: 9.1.3+9.1.3+main.9b69c82a
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 slf4jfixer PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 OptiFine TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
		 Vivecraft TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.18.2-20220404.173914-srg.jar             |Minecraft                     |minecraft                     |1.18.2              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		blueprint-1.18.2-5.5.0.jar                        |Blueprint                     |blueprint                     |5.5.0               |DONE      |Manifest: NOSIGNATURE
		VivecraftForgeExtensions-1.18.2-1.3.3.jar         |Vivecraft Forge Extensions    |vivecraftforgeextensions      |1.3.3               |DONE      |Manifest: NOSIGNATURE
		personality-1.18.2-2.0.0.jar                      |Personality                   |personality                   |2.0.0               |DONE      |Manifest: NOSIGNATURE
		FNAF Mod Update 3 Patch 1.jar                     |The Five Nights at Freddy's Mo|fnaf_mod                      |3                   |DONE      |Manifest: NOSIGNATURE
		BadMobs-1.18.2-13.01.jar                          |BadMobs                       |badmobs                       |13.01               |DONE      |Manifest: NOSIGNATURE
		forge-1.18.2-40.1.51-universal.jar                |Forge                         |forge                         |40.1.51             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		vrapi-1.4.0-1.18.2.jar                            |VR API                        |vrapi                         |1.4.0               |DONE      |Manifest: NOSIGNATURE
		MorePlayerModels-1.18.2.20220801.jar              |More Player Models            |moreplayermodels              |1.18.2.20220801     |DONE      |Manifest: NOSIGNATURE
		UniversalClockHUD-FORGE-1.18.2-v1.5.0.jar         |Universal Clock HUD           |universalclockhud             |1.18.2-v1.5.0       |DONE      |Manifest: NOSIGNATURE
		[1.18.2] SecurityCraft v1.9.3.1.jar               |SecurityCraft                 |securitycraft                 |1.9.3.1             |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: f9094a32-fb6a-429f-a669-9e6de3365289
	FML: 40.1
	Forge: net.minecraftforge:40.1.51

**Comment by wyldcrd** [comment]
That is what we needed.

**Comment by KingGl1tch** [comment]
ok so is there anyway i can get this work?

**Comment by BenRandall26** [comment]
Was there an update for this? I'm looking into a crash happening in my modded server where the camera monitor crashes when opened.
